### PR TITLE
Don't SQL join community_memberships if not needed

### PR DESCRIPTION
**Pull request by rap1ds**

### CODE REVIEW

**Comment by rap1ds** [comment]
Waiting still tests to pass, but after that this can be reviewed.

**Comment by rap1ds** [comment]
Tests are failing, needs more work.

**Comment by rap1ds** [comment]
Now tests are fixed. One test is still failing but that's random :(

**Comment by sktoiva** [comment]
LGTM, didn't test so test thoroughly.

**Pull request merged**
