### PR TITLE
old bug: bubble-price is not visible.

### PR DESCRIPTION
**Pull request by Gnito**

### CODE REVIEW

**Comment by rap1ds** [comment]
Can you add a screenshot to the pull request?

**Comment by Gnito** [comment]
screen shot 2016-02-08 at 17 03 19

**Comment by Gnito** [comment]
I also checked if this bubble price contain new unit types - they didn't. So, code is now updated with new commit. 
(N.B. if unit price doesn't fit to its space, it will have ellipsis.)

screen shot 2016-02-08 at 18 13 21

**Comment by rap1ds** [comment]
Looks good to me :+1:

**Pull request merged**
