### PR TITLE
Add Mongolian

### PR DESCRIPTION
**Pull request by rap1ds**

### CODE REVIEW

**Comment by bipashant** [comment]
@rap1ds What'll be the value for `ident`, `name`, `language`,  `region`, `fallback`.I'm trying to add Nepali language but getting errors like `np is not a valid locales`.

**Comment by mporkola** [comment]
@bipashant, the ISO 639-1 language code for Nepali is `ne`, not `np`. The region code for Nepal is `NP`. The best forum for this kind of questions is our [Flowdock chat](https://www.flowdock.com/invitations/de227bdbe48d24c31a6b749933d3b4eca82e307c), however :)

**Comment by mporkola** [comment]
@rap1ds, :+1:

**Comment by bipashant** [comment]
@mporkola Thanks a lot brother

**Comment by rap1ds** [comment]
I'll close this now, let's reopen it if needed.

**Pull request closed without merging**
