### PR TITLE
Use font-awesome as gem dependency

### PR DESCRIPTION
**Pull request by matheusvetor**
handle font-awesome assets with proper gem

### CODE REVIEW

**Comment by rap1ds** [comment]
@matheusvetor Circle CI error: `undefined method `tag' for #<Admin::GettingStartedGuideController:0x007fab78b65938> (NoMethodError)`

**Comment by matheusvetor** [comment]
@rap1ds Sorry my bad. I never used the CircleCI

**Comment by rap1ds** [comment]
The tests are still failing. Maybe you could undo the refactoring you made to icon_helper.rb file?

**Comment by matheusvetor** [comment]
Sentimental code. But still failing.

**Pull request closed without merging**
