### PR TITLE
Improved email notification content a bit.

### PR DESCRIPTION
**Pull request by thomasmalbaux**

### CODE REVIEW

**Comment by sktoiva** [comment]
Why isn't this completely translated? Because it's sent only to admins?

**Comment by thomasmalbaux** [comment]
Unfortunately no idea. @rap1ds suggested to change this file directly instead of moving to a translation approach as there might be underlying reasons for the current setup but we didn't investigate.
If you have some insights about this, happy to learn more!

**Comment by rap1ds** [comment]
How to move this forward? @sktoiva was that only a question or also a suggestion to translate the message?

**Comment by sktoiva** [comment]
It was only a question. If you have already done the pondering regarding the issue just move forward.

**Pull request merged**
