### PR TITLE
Specify to infer spec type from file location

### PR DESCRIPTION
**Pull request by bingxie**
To get rid of the warning for the coming rspec3.

### CODE REVIEW

**Comment by rap1ds** [comment]
I will leave this open for discussion, but I have a feeling that instead of this, we could just add the test type to each RSpec file. To me this feels like unnecessary magic, which also prevents us from arranging the specs in different directory structure.

**Comment by bingxie** [comment]
This will let us still keep the dir convention in mind. But if we decided to add type to each file. After we finished the change, we can get rid of this magic.

**Comment by ovan** [comment]
Hi @bingxie. I'm closing this now as we have not yet upgraded to rspec3. I prefer to force an explicit choice about this at upgrade time instead.

**Comment by bingxie** [comment]
That's ok!

**Pull request closed without merging**
