### PR TITLE
Enable location search with Sphinx

### PR DESCRIPTION
**Pull request by zenikk**

### CODE REVIEW

**Comment by liteultom** [comment]
Hi @zenikk ! Tried to implement this myself using your commit. I can enable location search but when I try to use it, I get the following error : 

`index listing_core,listing_delta: parse error: unknown column: latitude - SELECT GEODIST(0.8527087756759569, 0.04105401863784605, latitude, longitude) AS geodist, * FROM `listing_core`, `listing_delta` WHERE `community_id` = 1 AND `category_hidden` = 0 AND `sphinx_deleted` = 0 ORDER BY `geodist` ASC LIMIT 0, 24 OPTION field_weights=(title=10, category=8, description=3), max_query_time=1000; SHOW META`

Any lead to solve this is welcome. Thanks a lot for your original commit !

**Comment by zenikk** [comment]
@liteultom 
Run rake ts:rebuild to update index

**Comment by liteultom** [comment]
So this is what I was missing ! Now I get a different error ( `no enabled local indexes to search` ) even with the `searchd` started but I will figure that one by myself, must be on my side. Thanks a lot for your help

**Comment by zenikk** [comment]
@liteultom
Seems to be an issue with latest mysql 5.7.x releases, need to check.
Meanwhile, possible workaround :
https://stackoverflow.com/a/38179956

**Comment by liteultom** [comment]
Yup, I was just coming here to share that.
Indeed, mysql 5.7 has `sql_mode=only_full_group_by` activated by default, and it is very restrictive. Deactivating it solved the problem, index now builds without error and localised search is working ! cheers !

**Comment by zenikk** [comment]
@liteultom 

Maybe a better change is to fix index query with explicit aggregates for lat/lng:
```diff
--- a/app/indices/listing_index.rb
+++ b/app/indices/listing_index.rb
@@ -26,6 +26,8 @@ if APP_CONFIG.use_thinking_sphinx_indexing.to_s.casecmp("true") == 0
     has community_id
     has custom_dropdown_field_values.selected_options.id, :as => :custom_dropdown_field_options, :type => :integer, :multi => true
     has custom_checkbox_field_values.selected_options.id, :as => :custom_checkbox_field_options, :type => :integer, :multi => true
+    has 'RADIANS(MIN(locations.latitude))', as: :latitude, type: :float
+    has 'RADIANS(MIN(locations.longitude))', as: :longitude, type: :float
 
     set_property :enable_star => true
 
```

**Comment by ali-ssi** [comment]
@zenikk 
@liteultom 
Can anyone of you faced this ERROR? I used the same code and searchd is also ran but getting this ERROR.


no enabled local indexes to search - SELECT GEODIST(0.5492498796148595, 1.2963049046752444, latitude, longitude) AS geodist, * FROM `listing_core`, `listing_delta` WHERE `community_id` = 9528 AND `geodist` BETWEEN 0 AND 50000.0 AND `sphinx_deleted` = 0 ORDER BY `sort_date` DESC LIMIT 0, 30 OPTION field_weights=(title=10, category=8, description=3); SHOW META

**Comment by nmella** [comment]
Thanks @zenikk for this contribution. 

I merge this PR to the recent Sharetribe code, but I am missing the "Keyword & Location" option in the settings panel:

image

Maybe I need to add some flag to the `features_flag` table ?

Thanks.

**Comment by nmella** [comment]
> but I am missing the "Keyword & Location" option in the settings panel:

You need to add the features `manage_searchpage` and `topbar_v1` to the  <kbd>feature_flags </kbd> table:

**Pull request closed without merging**
